import { getInitData } from "./telegram";
type RuntimeConfig = { apiUrl?: string };

let _runtimeConfigPromise: Promise<RuntimeConfig> | null = null;

async function getApiBase(): Promise<string> {
  // In the browser we read runtime-config.json generated by start_all.sh (no .env required)
  if (typeof window !== "undefined") {
    if (!_runtimeConfigPromise) {
      _runtimeConfigPromise = fetch("/runtime-config.json", { cache: "no-store" })
        .then(async (r) => (r.ok ? (await r.json()) : ({})))
        .catch(() => ({}));
    }
    const cfg = await _runtimeConfigPromise;
    if (cfg && typeof cfg.apiUrl === "string" && cfg.apiUrl.trim()) return cfg.apiUrl.trim();
  }
  // Server-side fallback
  return "http://localhost:8787";
}
async function req(path: string, opts: RequestInit = {}) {
  const initData = typeof window !== "undefined" ? getInitData() : "";
  const headers: any = { "Content-Type": "application/json", ...(opts.headers || {}) };
  if (initData) headers["x-init-data"] = initData;
  const API = await getApiBase();
  const res = await fetch(`${API}${path}`, { ...opts, headers });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw Object.assign(new Error("API error"), { status: res.status, data });
  return data;
}
export const api = {
  me: () => req("/me"),
  balance: () => req("/balance"),
  walletSet: (address: string) => req("/wallet/set", { method: "POST", body: JSON.stringify({ address }) }),
  jackpotState: () => req("/jackpot/state"),
  bet: (amount_ton: string) => req("/jackpot/bet", { method: "POST", body: JSON.stringify({ amount_ton }) }),
  transactions: () => req("/transactions"),
  requirements: () => req("/requirements"),
  depositCreate: (amount_ton: string) => req("/deposits/create", { method: "POST", body: JSON.stringify({ amount_ton }) }),
  depositTonConnectCreate: (amount_ton: string) => req("/deposits/tonconnect/create", { method: "POST", body: JSON.stringify({ amount_ton }) }),
  depositTonConnectSubmit: (deposit_id: number, source_address: string) => req("/deposits/tonconnect/submit", { method: "POST", body: JSON.stringify({ deposit_id, source_address }) }),
  depositCryptoBotCreate: (amount_ton: string) => req("/deposits/cryptobot/create", { method: "POST", body: JSON.stringify({ amount_ton }) }),
  withdrawRequest: (amount_ton: string) => req("/withdraw/request", { method: "POST", body: JSON.stringify({ amount_ton }) }),
  dailyStatus: () => req("/bonuses/status"),
  dailyClaim: () => req("/bonuses/daily/claim", { method:"POST", body:"{}" }),
  cashbackClaim: () => req("/bonuses/cashback/claim", { method:"POST", body:"{}" }),
  referralClaim: () => req("/bonuses/referral/claim", { method:"POST", body:"{}" }),
  promoActivate: (code: string) => req("/promo/activate", { method:"POST", body: JSON.stringify({ code }) }),
  refStats: () => req("/referrals/stats"),
  leaderboard: () => req("/leaderboard/top"),
  prizes: () => req("/tournament/prizes"),
};
